### ISSUE TITLE
My Thoughts and Offer of Assistance

### ISSUE THREAD

**Issue by gek169** [wijiler/Quartzz#2]
We chatted on discord, and I thought I'd leave my thoughts for you here.

I don't know if this is the right spot for this. My apologies if it isn't. Feel free to delete this if it bothers you. It'll be my fault, not yours.

THOUGHTS ON YOUR FRONT PAGE ROADMAP

I would advise doing your constexpr stuff (or whatever the equivalent is for your project) early on, as it will give you an idea of how you'll do parsing for the rest of your project.

My honest recommendation is this: Think carefully about what the "core ideas" are for your project. Figure out what the end goal of Quartzz is. What makes it "better" or "more powerful".

Don't be discouraged if you can't think of a reason. The reason could be as simple as "I want it to look different". That's totally legitimate.

THOUGHTS ON  YOUR SYNTAX EXAMPLE

I have personal opinions of preference in syntax, but the real "gotcha" i have is the usage of capital letters in type names. Capital letters require pressing 'shift' which means extra keystrokes. Pressing shift is something that should be avoided where possible because it tires your fingers.

it's especially strange that you put capital letters in the middle of type names but not at the beginning.

THOUGHTS ON QZG

Editable parser grammar? I think you could probably allow defining "hooks" into the pre-existing grammar (to allow for arbitrary new parsers and parser rules), but if you want to literally change the pre-existing parser that might be very complicated.

I see multiple routes for this-

I went the route of defining a dedicated "metaprogramming operator" which invokes a function to take over parsing. This avoids the need you describe in your file of having to write a parser generator (you don't need to, because the user writes their own parser. If they want a parser generator, they write that too).

You could also go the route of allowing the addition of new rules into your parser. For a recursive descent parser (The easiest type to write!) this simply means adding the ability to add new recursive descent levels. It would function identically to the parsehook but not require explicitly invoking the hook when you want to use that language.

QIR

I had similar thoughts for creating a "universal IR". I ended up just using Seabass's AST as the universal IR.

If you want something like a bytecode that will be more involved and likely require you to make assumptions about the target platform.

Can't comment on your syntax, as I don't understand it.

I can comment that adding threads to your language seems cool. I have always considered multithreading support to be a secondary concern (Programs are typically single threaded and multithreading is rarely of very high value, and the decisions made to make multithreading efficient on a particular platform are likely platform-specific).

YOUR JAI CODE

I don't know jai, but I can comment that it looks fairly clean.

MY OFFER

As you know from our discussion on discord as well as what I wrote here, I am working on a language of my own (using the blessings of our Lord Jesus Christ, which I do not deserve).

My language already compiles to C and has the ability to define custom syntaxes. I already have a compiletime recursive descent parser system, and I just wrote the Universal AST.

It might be possible, given your language description, for me to implement Quartzz (or some close approximation) inside of SEABASS. 

This would serve a real purpose in my work (It would demonstrate and test Seabass's capabilities as a metaprogramming language) as well as make your programming language "real" with potentially far less effort than writing it on your own in Jai.

However, if we did that, I would want the implementation to be public domain. It definitely has to be if we're going to put it in the seabass repository.

I don't think you'd have to learn Seabass to work with me on it, you'd just need to provide descriptions of what the language looks like to me and I could write the parser, the AST, and the converter to Seabass code.

If your language maps nearly 1:1 with C, then it should be possible to do a direct translation to seabass, albeit with a few gotchas (SEABASS does not have short circuiting, for instance).

What do you say?

**Comment by wijiler** [comment]
# Adressing your main concerns  

`My honest recommendation is this: Think carefully about what the "core ideas" are for your project. Figure out what the end goal of Quartzz is. What makes it "better" or "more powerful".`
The idea of quartzz is based on the idea that I want something I can quickly write, and something that other people can quickly write, I want to eliminate as much overhead as possible  
Rust has a similar concept, the thing about rust is that its borrowchecked, this forces a style of code on you, I want people to type what they want to type, thats why I plan to implement an  
extensible syntax. The reason its better would be because it doesnt get into your way, the endgoal is to make sense. Your code works how you tell it. The main problem I have with c that to be fair  
is an easy solution is memory errors. I am invisioning, a semi-memory safe language with both low level features and high level features. Another reason it could be considered "better"  
is that in my head at least its made with big projects in mind, I want your code to be readable, however the readability of your code also depends on you. The last reason/principle would be speed  
Fast compile times,and fast run times. (hopefully that makes sense)  
  
`it's especially strange that you put capital letters in the middle of type names but not at the beginning.`
the reason for something like uInt is just because in my head the u is like a modifier to the Int type making it unsigned  
the reason char isnt capitalized is because in my head its a small type, therefore small characters  
  
`Editable parser grammar? I think you could probably allow defining "hooks" into the pre-existing grammar (to allow for arbitrary new parsers and parser rules), but if you want to literally change the pre-existing parser that might be very complicated.`
The way I imagine this working is the parser reads from a file in your project and then can generate functions in the parsefunctions module and then add the rules to the parser, this may require some way to edit the lexer  
  
## Other things about quartzz

C interop is very important to me as a developer as I hate writing bindings and many of the most common libraries needed are written in c  
I havent fully fleshed out this concept but essentially the interop is added at the assembly level  

Function tags are important  
!! => main  
@! => spawn thread  
#! => meta function/macro  

main syntax

```go
imp std // imp is short for import, you can use either interchangebly
func main !! () {
    print("Foo")
    Int x = 2
    x = 6
    x = 37
    y = x + 0(x) + 1(x) // 37 + 2 + 6
    // fixed arrays 
    [Int|2] farr = [0,2]
    //farr[2] = 2 this is an error
    // we should also be able to have a fixed sized array due to time travel
    [Int|0(x)] farr2 = [1,2]
    // if there isnt a constant value at this time eg x is = a function call that cant be evaluated at compile time then we just evaluate to a dynamic array 
    // dyn arrays
    [Int] darr = [0,0,2] // evaluated to a 3 element array
    darr[3] = 1 // arr is now a 4 element array
    // not sure whether to implement nested functions or not
    //
    print("%",darr[2]) // string formatting
} 

// hopefully hygienic macros are implemented
func macroex #! () {
    /* macro stuff */
    // because hygienic macros are the way they are we also need to have something else to 
    /// access values outside of its own scope
}
// calling of a macro has to look a lil different from a function for readability and safety
// Something like <macroex()> maybe?
// threaded functions behave exactly like functions but on a new thread
// returning a value for a function
String exampleret () {
    return "example"
}
```

**Comment by gek169** [comment]
```
The idea of quartzz is based on the idea that I want something I can quickly write, and something that other people can quickly write, I want to eliminate as much overhead as possible
```
This is almost identical to my greater vision with seabass.

```
@! => spawn thread
```
I would advise against this. Having multiple threads start before main is called is... well it seems frought with peril.

Then again, maybe I'm wrong! I can tell you that it's not portable, though. You can't get that code to run (well) on a 6502.

```
I am invisioning, a semi-memory safe language with both low level features and high level features. Another reason it could be considered "better"
```
this sounds a lot like what I envision for OOPSY, which is the language I want to write inside of Seabass.
```
imp std
```
Seabass does not allow custom language syntaxes to open files on their own (They must use the token stream) so this will have to work by having `std`'s function prototypes and type declarations defined in the unit. It'll have to break down to `include` somehow if we want quartzz to be a DSL in Seabass.

```
Rust has a similar concept, the thing about rust is that its borrowchecked, this forces a style of code on you, I want people to type what they want to type, thats why I plan to implement an
extensible syntax.
```
I am working on a scheme for static analysis which will remove most of the "code style forcing" that Rust has. For instance, I believe lifetime annotations are entirely unnecessary.

**Comment by wijiler** [comment]
`I would advise against this. Having multiple threads start before main is called is... well it seems frought with peril.

Then again, maybe I'm wrong! I can tell you that it's not portable, though. You can't get that code to run (well) on a 6502.`

only should spawn a thread when called

**Comment by gek169** [comment]
> `I would advise against this. Having multiple threads start before main is called is... well it seems frought with peril.
> 
> Then again, maybe I'm wrong! I can tell you that it's not portable, though. You can't get that code to run (well) on a 6502.`
> 
> only should spawn a thread when called

Ah, ok, yeah that's more portable. Much better idea imo
